const formClientes = document.getElementById('formClientes')
const modalClientes = document.getElementById('modalClientes')
const tableClientes = document.getElementById('tableClientes')

const btNovoCliente = document.getElementById('btNovoCliente')
const btVoltarModal = document.getElementById('btVoltar')

const nomeInput = document.getElementById('nomeInput')
const cpfInput = document.getElementById('cpfInput')
const enderecoInput = document.getElementById('enderecoInput')
const numeroInput = document.getElementById('numeroInput')
const bairroInput = document.getElementById('bairroInput')
const cidadeInput = document.getElementById('cidadeInput')
const estadoInput = document.getElementById('estadoInput')
const cepInput = document.getElementById('cepInput')
const dtNascInput = document.getElementById('dtNascInput')
const profissaoInput = document.getElementById('profissaoInput')
const emailInput = document.getElementById('emailInput')
const foneInput = document.getElementById('foneInput')
